version: '3'
services:
  top-api:
    image: ghcr.io/yushkevich-a-a/test-nest/test-nest:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
